services:
  frontend:
    image: nginx:alpine
    container_name: sr-frontend
    ports:
      - "8090:80"
    volumes:
      - ./frontend/index.html:/usr/share/nginx/html/index.html:ro
    networks:
      - app-frontend
    depends_on:
      - backend

  backend:
    image: alpine:3.20
    container_name: sr-backend
    command: sleep infinity
    networks:
      - app-frontend
      - app-backend
    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: sr-database
    environment:
      MYSQL_ROOT_PASSWORD: devops123
      MYSQL_DATABASE: testdb
    networks:
      - app-backend

networks:
  app-frontend:
    driver: bridge
  app-backend:
    driver: bridge
